#!/bin/sh
export SPRING_MAIL_HOST=smtp-relay.brevo.com
export SPRING_MAIL_PORT=587
export SPRING_MAIL_USERNAME=noreply@devalgas.com
export SPRING_MAIL_PASSWORD=
export SPRING_MAIL_PROPERTIES_MAIL_SMTP_AUTH=true
export SPRING_MAIL_PROPERTIES_MAIL_SMTP_STARTTLS_ENABLE=true
export JHIPSTER_MAIL_FROM=noreply@devalgas.com
export RECAPTCHA_SECRET=6LewAUwsAAAAABLATqSXUf-MHblYcvuXwKZlLWCJ



echo "$SPRING_MAIL_PASSWORD"
echo "$RECAPTCHA_SECRET"
echo "$SPRING_MAIL_USERNAME"
