package com.devalgas.blog.domain;

import static org.assertj.core.api.Assertions.assertThat;

public class AppInfoAsserts {

    /**
     * Asserts that the entity has all properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertAppInfoAllPropertiesEquals(AppInfo expected, AppInfo actual) {
        assertAppInfoAutoGeneratedPropertiesEquals(expected, actual);
        assertAppInfoAllUpdatablePropertiesEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all updatable properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertAppInfoAllUpdatablePropertiesEquals(AppInfo expected, AppInfo actual) {
        assertAppInfoUpdatableFieldsEquals(expected, actual);
        assertAppInfoUpdatableRelationshipsEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all the auto generated properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertAppInfoAutoGeneratedPropertiesEquals(AppInfo expected, AppInfo actual) {
        assertThat(actual)
            .as("Verify AppInfo auto generated properties")
            .satisfies(a -> assertThat(a.getId()).as("check id").isEqualTo(expected.getId()));
    }

    /**
     * Asserts that the entity has all the updatable fields set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertAppInfoUpdatableFieldsEquals(AppInfo expected, AppInfo actual) {
        assertThat(actual)
            .as("Verify AppInfo relevant properties")
            .satisfies(a -> assertThat(a.getKeyInfo()).as("check keyInfo").isEqualTo(expected.getKeyInfo()))
            .satisfies(a -> assertThat(a.getValueInfo()).as("check valueInfo").isEqualTo(expected.getValueInfo()));
    }

    /**
     * Asserts that the entity has all the updatable relationships set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertAppInfoUpdatableRelationshipsEquals(AppInfo expected, AppInfo actual) {
        assertThat(actual)
            .as("Verify AppInfo relationships")
            .satisfies(a -> assertThat(a.getHeaders()).as("check headers").isEqualTo(expected.getHeaders()))
            .satisfies(a -> assertThat(a.getFooters()).as("check footers").isEqualTo(expected.getFooters()));
    }
}
