package com.devalgas.blog.domain;

import static com.devalgas.blog.domain.AssertUtils.zonedDataTimeSameInstant;
import static org.assertj.core.api.Assertions.assertThat;

public class ArticleAsserts {

    /**
     * Asserts that the entity has all properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertArticleAllPropertiesEquals(Article expected, Article actual) {
        assertArticleAutoGeneratedPropertiesEquals(expected, actual);
        assertArticleAllUpdatablePropertiesEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all updatable properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertArticleAllUpdatablePropertiesEquals(Article expected, Article actual) {
        assertArticleUpdatableFieldsEquals(expected, actual);
        assertArticleUpdatableRelationshipsEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all the auto generated properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertArticleAutoGeneratedPropertiesEquals(Article expected, Article actual) {
        assertThat(actual)
            .as("Verify Article auto generated properties")
            .satisfies(a -> assertThat(a.getId()).as("check id").isEqualTo(expected.getId()));
    }

    /**
     * Asserts that the entity has all the updatable fields set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertArticleUpdatableFieldsEquals(Article expected, Article actual) {
        assertThat(actual)
            .as("Verify Article relevant properties")
            .satisfies(a -> assertThat(a.getLabelEn()).as("check labelEn").isEqualTo(expected.getLabelEn()))
            .satisfies(a -> assertThat(a.getLabelFr()).as("check labelFr").isEqualTo(expected.getLabelFr()))
            .satisfies(a -> assertThat(a.getDescriptionFr()).as("check descriptionFr").isEqualTo(expected.getDescriptionFr()))
            .satisfies(a -> assertThat(a.getDescriptionEn()).as("check descriptionEn").isEqualTo(expected.getDescriptionEn()))
            .satisfies(a -> assertThat(a.getMarkdownFr()).as("check markdownFr").isEqualTo(expected.getMarkdownFr()))
            .satisfies(a ->
                assertThat(a.getMarkdownFrContentType()).as("check markdownFr contenty type").isEqualTo(expected.getMarkdownFrContentType())
            )
            .satisfies(a -> assertThat(a.getMarkdownEn()).as("check markdownEn").isEqualTo(expected.getMarkdownEn()))
            .satisfies(a ->
                assertThat(a.getMarkdownEnContentType()).as("check markdownEn contenty type").isEqualTo(expected.getMarkdownEnContentType())
            )
            .satisfies(a -> assertThat(a.getStatus()).as("check status").isEqualTo(expected.getStatus()))
            .satisfies(a -> assertThat(a.getDate()).as("check date").usingComparator(zonedDataTimeSameInstant).isEqualTo(expected.getDate())
            )
            .satisfies(a -> assertThat(a.getBadge()).as("check badge").isEqualTo(expected.getBadge()))
            .satisfies(a -> assertThat(a.getBadgeContentType()).as("check badge contenty type").isEqualTo(expected.getBadgeContentType()))
            .satisfies(a -> assertThat(a.getBanner()).as("check banner").isEqualTo(expected.getBanner()))
            .satisfies(a -> assertThat(a.getBannerContentType()).as("check banner contenty type").isEqualTo(expected.getBannerContentType())
            )
            .satisfies(a -> assertThat(a.getViews()).as("check views").isEqualTo(expected.getViews()))
            .satisfies(a -> assertThat(a.getStars()).as("check stars").isEqualTo(expected.getStars()));
    }

    /**
     * Asserts that the entity has all the updatable relationships set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertArticleUpdatableRelationshipsEquals(Article expected, Article actual) {
        assertThat(actual)
            .as("Verify Article relationships")
            .satisfies(a -> assertThat(a.getCategoryArticles()).as("check categoryArticles").isEqualTo(expected.getCategoryArticles()));
    }
}
