package com.devalgas.blog.domain;

import static org.assertj.core.api.Assertions.assertThat;

public class CategoryArticleAsserts {

    /**
     * Asserts that the entity has all properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertCategoryArticleAllPropertiesEquals(CategoryArticle expected, CategoryArticle actual) {
        assertCategoryArticleAutoGeneratedPropertiesEquals(expected, actual);
        assertCategoryArticleAllUpdatablePropertiesEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all updatable properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertCategoryArticleAllUpdatablePropertiesEquals(CategoryArticle expected, CategoryArticle actual) {
        assertCategoryArticleUpdatableFieldsEquals(expected, actual);
        assertCategoryArticleUpdatableRelationshipsEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all the auto generated properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertCategoryArticleAutoGeneratedPropertiesEquals(CategoryArticle expected, CategoryArticle actual) {
        assertThat(actual)
            .as("Verify CategoryArticle auto generated properties")
            .satisfies(a -> assertThat(a.getId()).as("check id").isEqualTo(expected.getId()));
    }

    /**
     * Asserts that the entity has all the updatable fields set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertCategoryArticleUpdatableFieldsEquals(CategoryArticle expected, CategoryArticle actual) {
        assertThat(actual)
            .as("Verify CategoryArticle relevant properties")
            .satisfies(a -> assertThat(a.getLabel()).as("check label").isEqualTo(expected.getLabel()))
            .satisfies(a -> assertThat(a.getCode()).as("check code").isEqualTo(expected.getCode()))
            .satisfies(a -> assertThat(a.getBadge()).as("check badge").isEqualTo(expected.getBadge()))
            .satisfies(a -> assertThat(a.getBadgeContentType()).as("check badge contenty type").isEqualTo(expected.getBadgeContentType()))
            .satisfies(a -> assertThat(a.getDescriptionFr()).as("check descriptionFr").isEqualTo(expected.getDescriptionFr()))
            .satisfies(a -> assertThat(a.getDescriptionEn()).as("check descriptionEn").isEqualTo(expected.getDescriptionEn()));
    }

    /**
     * Asserts that the entity has all the updatable relationships set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertCategoryArticleUpdatableRelationshipsEquals(CategoryArticle expected, CategoryArticle actual) {
        assertThat(actual)
            .as("Verify CategoryArticle relationships")
            .satisfies(a -> assertThat(a.getArticles()).as("check articles").isEqualTo(expected.getArticles()));
    }
}
