package com.devalgas.blog.domain;

import static org.assertj.core.api.Assertions.assertThat;

public class FootersAsserts {

    /**
     * Asserts that the entity has all properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertFootersAllPropertiesEquals(Footers expected, Footers actual) {
        assertFootersAutoGeneratedPropertiesEquals(expected, actual);
        assertFootersAllUpdatablePropertiesEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all updatable properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertFootersAllUpdatablePropertiesEquals(Footers expected, Footers actual) {
        assertFootersUpdatableFieldsEquals(expected, actual);
        assertFootersUpdatableRelationshipsEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all the auto generated properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertFootersAutoGeneratedPropertiesEquals(Footers expected, Footers actual) {
        assertThat(actual)
            .as("Verify Footers auto generated properties")
            .satisfies(a -> assertThat(a.getId()).as("check id").isEqualTo(expected.getId()));
    }

    /**
     * Asserts that the entity has all the updatable fields set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertFootersUpdatableFieldsEquals(Footers expected, Footers actual) {
        assertThat(actual)
            .as("Verify Footers relevant properties")
            .satisfies(a -> assertThat(a.getLogoFooters()).as("check logoFooters").isEqualTo(expected.getLogoFooters()))
            .satisfies(a ->
                assertThat(a.getLogoFootersContentType())
                    .as("check logoFooters contenty type")
                    .isEqualTo(expected.getLogoFootersContentType())
            );
    }

    /**
     * Asserts that the entity has all the updatable relationships set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertFootersUpdatableRelationshipsEquals(Footers expected, Footers actual) {
        // empty method
    }
}
