package com.devalgas.blog.domain;

import static org.assertj.core.api.Assertions.assertThat;

public class HeadersAsserts {

    /**
     * Asserts that the entity has all properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertHeadersAllPropertiesEquals(Headers expected, Headers actual) {
        assertHeadersAutoGeneratedPropertiesEquals(expected, actual);
        assertHeadersAllUpdatablePropertiesEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all updatable properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertHeadersAllUpdatablePropertiesEquals(Headers expected, Headers actual) {
        assertHeadersUpdatableFieldsEquals(expected, actual);
        assertHeadersUpdatableRelationshipsEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all the auto generated properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertHeadersAutoGeneratedPropertiesEquals(Headers expected, Headers actual) {
        assertThat(actual)
            .as("Verify Headers auto generated properties")
            .satisfies(a -> assertThat(a.getId()).as("check id").isEqualTo(expected.getId()));
    }

    /**
     * Asserts that the entity has all the updatable fields set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertHeadersUpdatableFieldsEquals(Headers expected, Headers actual) {
        assertThat(actual)
            .as("Verify Headers relevant properties")
            .satisfies(a -> assertThat(a.getLogoHeaders()).as("check logoHeaders").isEqualTo(expected.getLogoHeaders()))
            .satisfies(a ->
                assertThat(a.getLogoHeadersContentType())
                    .as("check logoHeaders contenty type")
                    .isEqualTo(expected.getLogoHeadersContentType())
            );
    }

    /**
     * Asserts that the entity has all the updatable relationships set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertHeadersUpdatableRelationshipsEquals(Headers expected, Headers actual) {
        // empty method
    }
}
