package com.devalgas.blog.domain;

import static com.devalgas.blog.domain.AssertUtils.zonedDataTimeSameInstant;
import static org.assertj.core.api.Assertions.assertThat;

public class SubscribeAsserts {

    /**
     * Asserts that the entity has all properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertSubscribeAllPropertiesEquals(Subscribe expected, Subscribe actual) {
        assertSubscribeAutoGeneratedPropertiesEquals(expected, actual);
        assertSubscribeAllUpdatablePropertiesEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all updatable properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertSubscribeAllUpdatablePropertiesEquals(Subscribe expected, Subscribe actual) {
        assertSubscribeUpdatableFieldsEquals(expected, actual);
        assertSubscribeUpdatableRelationshipsEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all the auto generated properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertSubscribeAutoGeneratedPropertiesEquals(Subscribe expected, Subscribe actual) {
        assertThat(actual)
            .as("Verify Subscribe auto generated properties")
            .satisfies(a -> assertThat(a.getId()).as("check id").isEqualTo(expected.getId()));
    }

    /**
     * Asserts that the entity has all the updatable fields set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertSubscribeUpdatableFieldsEquals(Subscribe expected, Subscribe actual) {
        assertThat(actual)
            .as("Verify Subscribe relevant properties")
            .satisfies(a -> assertThat(a.getEmail()).as("check email").isEqualTo(expected.getEmail()))
            .satisfies(a -> assertThat(a.getLangKey()).as("check langKey").isEqualTo(expected.getLangKey()))
            .satisfies(a -> assertThat(a.getCountryKey()).as("check countryKey").isEqualTo(expected.getCountryKey()))
            .satisfies(a -> assertThat(a.getDate()).as("check date").usingComparator(zonedDataTimeSameInstant).isEqualTo(expected.getDate())
            );
    }

    /**
     * Asserts that the entity has all the updatable relationships set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertSubscribeUpdatableRelationshipsEquals(Subscribe expected, Subscribe actual) {
        // empty method
    }
}
